### ISSUE TITLE
USER STORY: Add additional input to poll submission

### ISSUE THREAD

**Issue by ashraafa** [ashraafa/Agile-Project#5]
As an **administrator** I can **pick the expiry date while punblishing the poll** so that **I can automatically hide the poll**

## Acceptance Criteria
* The poll should disappear at 11:59 PM on the target date
*  The real estate of the "Poll" should be reserved on the home page with a message that says "Stay Tuned, a new poll is coming soon" if no other poll is active
*  The administrator expiry date should be at least 3 days aftre the current date.

## Tasks
- [ ]  Update the admin module view: the poll design (HTML and CSS) to include date picker
- [ ] Update the website view: show "Stay tuned, a new poll is coming
- [ ] Create a Javascript fucntion to validate the date is least after 3 days.
- [ ] Create a job to check expired Polls everyday at 11:59 PM and Hide them
- [ ] Update the controller function
- [ ] Update the unit testscripts
- [ ] Test the functionality
